esphome:
  platformio_options:
    build_flags:
      - "-D HAS_DS"
  on_boot:
    then:
      # read the RTC time once when the system boots
      ds1307.read_time:
      
time:
  - platform: ds1307
    id: ds1307_time
    update_interval: 1d
  - id: !extend esptime
    on_time_sync:
      then:
        # ... and update the RTC when the synchronization was successful
        ds1307.write_time:
